Add slither validation to CI jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,7 +24,8 @@ jobs:
             - "vendor"
 
   build_check:
-    machine: true
+    machine:
+      image: ubuntu-1604:201903-01
     working_directory: /home/circleci/github.com/tokencard/contracts
     steps:
       - checkout
@@ -37,27 +38,87 @@ jobs:
   mythril:
     docker:
       - image: mythril/myth:0.21.19
-    working_directory: /src
+    working_directory: /tmp/contracts
+    parallelism: 6
     steps:
       - checkout
       - run:
-          command: myth analyze ./contracts/oracle.sol
-          no_output_timeout: 1h
+          working_directory: contracts
+          command: |
+            if [[ "${CIRCLE_NODE_INDEX}" == 0 ]]; then
+              myth analyze ./oracle.sol --execution-timeout=1800
+            fi
+          no_output_timeout: 45m
       - run:
-          command: myth analyze ./contracts/wallet.sol
-          no_output_timeout: 1h
+          working_directory: contracts
+          command: |
+            if [[ "${CIRCLE_NODE_INDEX}" == 1 ]]; then
+              myth analyze ./wallet.sol --execution-timeout=1800
+            fi
+          no_output_timeout: 45m
       - run:
-          command: myth analyze ./contracts/licence.sol
-          no_output_timeout: 1h
+          working_directory: contracts
+          command: |
+            if [[ "${CIRCLE_NODE_INDEX}" == 2 ]]; then
+              myth analyze ./holder.sol --execution-timeout=1800
+            fi
+          no_output_timeout: 45m 
       - run:
-          command: myth analyze ./contracts/holder.sol
-          no_output_timeout: 1h
+          working_directory: contracts
+          command: |
+            if [[ "${CIRCLE_NODE_INDEX}" == 3 ]]; then
+              myth analyze ./licence.sol --execution-timeout=1800
+            fi
+          no_output_timeout: 45m
       - run:
-          command: myth analyze ./contracts/tokenWhitelist.sol
-          no_output_timeout: 1h
+          working_directory: contracts
+          command: |
+            if [[ "${CIRCLE_NODE_INDEX}" == 4 ]]; then
+              myth analyze ./tokenWhitelist.sol --execution-timeout=1800
+            fi
+          no_output_timeout: 45m
       - run:
-          command: myth analyze ./contracts/walletDeployer.sol
-          no_output_timeout: 1h
+          working_directory: contracts
+          command: |
+            if [[ "${CIRCLE_NODE_INDEX}" == 5 ]]; then
+              myth analyze ./walletDeployer.sol --execution-timeout=1800
+            fi
+          no_output_timeout: 45m
+
+  slither:
+    docker:
+      - image: trailofbits/eth-security-toolbox:latest
+    working_directory: /tmp/contracts
+    steps:
+      - checkout
+      - run:
+          command: solc-select 0.5.10
+      - run:
+          working_directory: contracts
+          command: slither ./wallet.sol || echo "export FAILED=true" >> $BASH_ENV
+          no_output_timeout: 15m
+      - run:
+          working_directory: contracts
+          command: slither ./oracle.sol || echo "export FAILED=true" >> $BASH_ENV
+          no_output_timeout: 15m
+      - run:
+          working_directory: contracts
+          command: slither ./licence.sol || echo "export FAILED=true" >> $BASH_ENV
+          no_output_timeout: 15m
+      - run:
+          working_directory: contracts
+          command: slither ./holder.sol || echo "export FAILED=true" >> $BASH_ENV  
+          no_output_timeout: 15m
+      - run:
+          working_directory: contracts
+          command: slither ./tokenWhitelist.sol || echo "export FAILED=true" >> $BASH_ENV
+          no_output_timeout: 15m
+      - run:
+          working_directory: contracts
+          command: slither ./walletDeployer.sol || echo "export FAILED=true" >> $BASH_ENV
+          no_output_timeout: 15m
+      - run:
+          command: test ! $FAILED
 
 workflows:
   version: 2
@@ -74,6 +135,10 @@ workflows:
             tags:
               ignore: ""
       - mythril:
+          filters:
+            tags:
+              ignore: ""
+      - slither:
           filters:
             tags:
               ignore: ""
